CREATE DATABASE IF NOT EXISTS steel_user_db DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS steel_product_db DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS steel_content_db DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
